class RoadSign {
  final String signImage, signName;

  RoadSign({required this.signImage, required this.signName});
}

List signName = [
  'Roundabout Ahead',
  'No Entry',
  'Speed Limit 50km/h',
  'Men At Work',
  'Left Hand Curve',
  'Narrow Road From Right',
  'Narrow Road from Both Sides',
  'Pedestrian Crossing',
  'Do Not Enter',
  'No Cars Allowed',
  'No Right Turn',
  'Stop',
  'No U-turn',
  'Traffic Signal',
  'Agricultural Vehicles',
  'Buses Prohibited',
  'Clearway No Stopping',
  'Crossroads',
  'Falling Rocks',
  'Give Way',
  'Low Flying Aircraft',
  'No Left Turn',
  'One Way Traffic',
  'Motor Vehicles Prohibited',
  'Parking Space',
  'Railway Level Crossing',
  'Sharp Deviation',
  'Side Road from Right',
  'Slippery Road',
  'Tunnel Ahead',
  'Two Way Traffic',
  'Uneven Road',
  'Goods Vehicle Exceeding 7.5t Weight',
  'Winding Road',
  'Wrong Way',
  'Zebra Crossing',
  'Electrified Overhead Cable Ahead',
  'Excessive Noise Prohibited',
  'Hump Bridge Ahead',
  'Solo Motorcycles Prohibited',
  'National Speed Limit Applies',
  'Parking Reserved for Buses',
  'Series of Bends',
  'T-Junction',
  'Vehicle Exceeding Length Prohibited',
  'Single Carriageway Ahead',
];

List signImage = [
  'assets/images/roundabout.jpg',
  'assets/images/noentry.jpg',
  'assets/images/speedlimit.jpg',
  'assets/images/menatwork.jpg',
  'assets/images/lefthandcurve.jpg',
  'assets/images/narrowroad.jpg',
  'assets/images/narrowroad2.jpg',
  'assets/images/pedestriancrossing.jpg',
  'assets/images/donotenter.jpg',
  'assets/images/nocarsallowed.jpg',
  'assets/images/norightturn.jpg',
  'assets/images/stop.jpg',
  'assets/images/nouturn.png',
  'assets/images/trafficsignal.png',
  'assets/images/agricultural.png',
  'assets/images/buses prohibited.png',
  'assets/images/clearwaynostopping.png',
  'assets/images/crossroads.png',
  'assets/images/fallingrock.png',
  'assets/images/giveway.png',
  'assets/images/lowaircraft.png',
  'assets/images/noleftturn.png',
  'assets/images/onewaytraffic.png',
  'assets/images/onlymotorvehicles.png',
  'assets/images/parkingspace.png',
  'assets/images/railwaylevelcrossing.png',
  'assets/images/sharpdeviation.png',
  'assets/images/sideroad.png',
  'assets/images/slipperyroad.png',
  'assets/images/tunnels.png',
  'assets/images/twowaytraffic.png',
  'assets/images/unevenroad.png',
  'assets/images/weight limit.png',
  'assets/images/windingroad.png',
  'assets/images/wrongway.png',
  'assets/images/zebracrossing.png',
  'assets/images/electrifiedoverheadcable.png',
  'assets/images/excessivenoiseprohibited.png',
  'assets/images/humpbridge.png',
  'assets/images/motorcyclesprohibited.png',
  'assets/images/nationalspeedlimitapplies.png',
  'assets/images/reservedforbuses.png',
  'assets/images/seriesofbends.png',
  'assets/images/Tjunction.png',
  'assets/images/vehicleexceedinglengthprohibited.png',
  'assets/images/singlecarriageway.png',
];

List<RoadSign> signs = [
  RoadSign(signImage: signImage[0], signName: signName[0]),
  RoadSign(signImage: signImage[1], signName: signName[1]),
  RoadSign(signImage: signImage[2], signName: signName[2]),
  RoadSign(signImage: signImage[3], signName: signName[3]),
  RoadSign(signImage: signImage[4], signName: signName[4]),
  RoadSign(signImage: signImage[5], signName: signName[5]),
  RoadSign(signImage: signImage[6], signName: signName[6]),
  RoadSign(signImage: signImage[7], signName: signName[7]),
  RoadSign(signImage: signImage[8], signName: signName[8]),
  RoadSign(signImage: signImage[9], signName: signName[9]),
  RoadSign(signImage: signImage[10], signName: signName[10]),
  RoadSign(signImage: signImage[11], signName: signName[11]),
  RoadSign(signImage: signImage[12], signName: signName[12]),
  RoadSign(signImage: signImage[13], signName: signName[13]),
  RoadSign(signImage: signImage[14], signName: signName[14]),
  RoadSign(signImage: signImage[15], signName: signName[15]),
  RoadSign(signImage: signImage[16], signName: signName[16]),
  RoadSign(signImage: signImage[17], signName: signName[17]),
  RoadSign(signImage: signImage[18], signName: signName[18]),
  RoadSign(signImage: signImage[19], signName: signName[19]),
  RoadSign(signImage: signImage[20], signName: signName[20]),
  RoadSign(signImage: signImage[21], signName: signName[21]),
  RoadSign(signImage: signImage[22], signName: signName[22]),
  RoadSign(signImage: signImage[23], signName: signName[23]),
  RoadSign(signImage: signImage[24], signName: signName[24]),
  RoadSign(signImage: signImage[25], signName: signName[25]),
  RoadSign(signImage: signImage[26], signName: signName[26]),
  RoadSign(signImage: signImage[27], signName: signName[27]),
  RoadSign(signImage: signImage[28], signName: signName[28]),
  RoadSign(signImage: signImage[29], signName: signName[29]),
  RoadSign(signImage: signImage[30], signName: signName[30]),
  RoadSign(signImage: signImage[31], signName: signName[31]),
  RoadSign(signImage: signImage[32], signName: signName[32]),
  RoadSign(signImage: signImage[33], signName: signName[33]),
  RoadSign(signImage: signImage[34], signName: signName[34]),
  RoadSign(signImage: signImage[35], signName: signName[35]),
  RoadSign(signImage: signImage[36], signName: signName[36]),
  RoadSign(signImage: signImage[37], signName: signName[37]),
  RoadSign(signImage: signImage[38], signName: signName[38]),
  RoadSign(signImage: signImage[39], signName: signName[39]),
  RoadSign(signImage: signImage[40], signName: signName[40]),
  RoadSign(signImage: signImage[41], signName: signName[41]),
  RoadSign(signImage: signImage[42], signName: signName[42]),
  RoadSign(signImage: signImage[43], signName: signName[43]),
  RoadSign(signImage: signImage[44], signName: signName[44]),
  RoadSign(signImage: signImage[45], signName: signName[45]),
];
