class RoadSignDetails {
  final String signImage, signDetails;

  RoadSignDetails({required this.signImage, required this.signDetails});
}


List signImage = [
  'assets/images/roundabout.jpg',
  'assets/images/noentry.jpg',
  'assets/images/speedlimit.jpg',
  'assets/images/menatwork.jpg',
  'assets/images/lefthandcurve.jpg',
  'assets/images/narrowroad.jpg',
  'assets/images/narrowroad2.jpg',
  'assets/images/pedestriancrossing.jpg',
  'assets/images/donotenter.jpg',
  'assets/images/nocarsallowed.jpg',
  'assets/images/norightturn.jpg',
  'assets/images/stop.jpg',
  'assets/images/nouturn.png',
  'assets/images/trafficsignal.png',
  'assets/images/agricultural.png',
  'assets/images/buses prohibited.png',
  'assets/images/clearwaynostopping.png',
  'assets/images/crossroads.png',
  'assets/images/fallingrock.png',
  'assets/images/giveway.png',
  'assets/images/lowaircraft.png',
  'assets/images/noleftturn.png',
  'assets/images/onewaytraffic.png',
  'assets/images/onlymotorvehicles.png',
  'assets/images/parkingspace.png',
  'assets/images/railwaylevelcrossing.png',
  'assets/images/sharpdeviation.png',
  'assets/images/sideroad.png',
  'assets/images/slipperyroad.png',
  'assets/images/tunnels.png',
  'assets/images/twowaytraffic.png',
  'assets/images/unevenroad.png',
  'assets/images/weight limit.png',
  'assets/images/windingroad.png',
  'assets/images/wrongway.png',
  'assets/images/zebracrossing.png',
  'assets/images/electrifiedoverheadcable.png',
  'assets/images/excessivenoiseprohibited.png',
  'assets/images/humpbridge.png',
  'assets/images/motorcyclesprohibited.png',
  'assets/images/nationalspeedlimitapplies.png',
  'assets/images/reservedforbuses.png',
  'assets/images/seriesofbends.png',
  'assets/images/Tjunction.png',
  'assets/images/vehicleexceedinglengthprohibited.png',
  'assets/images/singlecarriageway.png',
  'assets/images/roadnarrowsfrombothsides.png',
  'assets/images/sidewinds.png',
];

List signDetails = [
  'Indicates the presence of a roundabout ahead',
  'Entry into an area is prohibited'
  'Speed Limit of 50km/h',
  'Indicates men at work',
  'Warning of a curve on your left',
  'Approaching a narrow road on your right'
  'Approaching narrow roads from both sides',
  'Pedestrian crossing ahead',
  'Entry into an area is prohibited',
  'No power driven vehicles allowed',
  'Prohibited from turning on your right',
  'Mandatory to stop',
  'Prohibited from making a U-turn',
  'Approaching a traffic signal',
  'Warning of agricultural vehicles up ahead',
  'Buses not allowed into a particular area',
  'Prohibited from stopping at a particular area',
  'Approaching a crossroad',
  'Danger of falling rocks',
  'Give way to oncoming vehicles',
  'Anticipate noise from low flying aircrafts',
  'Prohibited from turning to your left',
  'Traffic in only one direction',
  'No motor vehicles allowed',
  'Availability of parking space',
  'Railway crossing up ahead',
  'Sharp deviation up ahead',
  'Side road joins to the main road from the right',
  'Indicates Slippery road up ahead',
  'Indicates a tunnel up ahead',
  'Traffic occuring from both directions',
  'Road up ahead is not smooth',
  'Goods vehicles exceeding said weight are prohibited',
  'Winding road up ahead',
  'Way not passable',
  'Zebra crossing up ahead',
  'Danger of electified cable',
  'Loud noises not allowed',
  'Hump bridge ahead',
  'Motorcycles not allowed',
  'National Speed Limit Applies',
  'Parking area is reserved for buses',
  'Indicates series of bends up ahead',
  'Indicates T shaped junction up ahead',
  'Vehicles exceeding specified length not allowed',
  'Single carriageway up ahead',
  'Approaching road which narrows from both sides',
  'Indicates strong winds in the area',
];


List<RoadSignDetails> signs = [
  RoadSignDetails(signImage: signImage[0], signDetails: signDetails[0]),
  RoadSignDetails(signImage: signImage[1], signDetails: signDetails[1]),
  RoadSignDetails(signImage: signImage[2], signDetails: signDetails[2]),
  RoadSignDetails(signImage: signImage[3], signDetails: signDetails[3]),
  RoadSignDetails(signImage: signImage[4], signDetails: signDetails[4]),
  RoadSignDetails(signImage: signImage[5], signDetails: signDetails[5]),
  RoadSignDetails(signImage: signImage[6], signDetails: signDetails[6]),
  RoadSignDetails(signImage: signImage[7], signDetails: signDetails[7]),
  RoadSignDetails(signImage: signImage[8], signDetails: signDetails[8]),
  RoadSignDetails(signImage: signImage[9], signDetails: signDetails[9]),
  RoadSignDetails(signImage: signImage[10], signDetails: signDetails[10]),
  RoadSignDetails(signImage: signImage[11], signDetails: signDetails[11]),
  RoadSignDetails(signImage: signImage[12], signDetails: signDetails[12]),
  RoadSignDetails(signImage: signImage[13], signDetails: signDetails[13]),
  RoadSignDetails(signImage: signImage[14], signDetails: signDetails[14]),
  RoadSignDetails(signImage: signImage[15], signDetails: signDetails[15]),
  RoadSignDetails(signImage: signImage[16], signDetails: signDetails[16]),
  RoadSignDetails(signImage: signImage[17], signDetails: signDetails[17]),
  RoadSignDetails(signImage: signImage[18], signDetails: signDetails[18]),
  RoadSignDetails(signImage: signImage[19], signDetails: signDetails[19]),
  RoadSignDetails(signImage: signImage[20], signDetails: signDetails[20]),
  RoadSignDetails(signImage: signImage[21], signDetails: signDetails[21]),
  RoadSignDetails(signImage: signImage[22], signDetails: signDetails[22]),
  RoadSignDetails(signImage: signImage[23], signDetails: signDetails[23]),
  RoadSignDetails(signImage: signImage[24], signDetails: signDetails[24]),
  RoadSignDetails(signImage: signImage[25], signDetails: signDetails[25]),
  RoadSignDetails(signImage: signImage[26], signDetails: signDetails[26]),
  RoadSignDetails(signImage: signImage[27], signDetails: signDetails[27]),
  RoadSignDetails(signImage: signImage[28], signDetails: signDetails[28]),
  RoadSignDetails(signImage: signImage[29], signDetails: signDetails[29]),
  RoadSignDetails(signImage: signImage[30], signDetails: signDetails[30]),
  RoadSignDetails(signImage: signImage[31], signDetails: signDetails[31]),
  RoadSignDetails(signImage: signImage[32], signDetails: signDetails[32]),
  RoadSignDetails(signImage: signImage[33], signDetails: signDetails[33]),
  RoadSignDetails(signImage: signImage[34], signDetails: signDetails[34]),
  RoadSignDetails(signImage: signImage[35], signDetails: signDetails[35]),
  RoadSignDetails(signImage: signImage[36], signDetails: signDetails[36]),
  RoadSignDetails(signImage: signImage[37], signDetails: signDetails[37]),
  RoadSignDetails(signImage: signImage[38], signDetails: signDetails[38]),
  RoadSignDetails(signImage: signImage[39], signDetails: signDetails[39]),
  RoadSignDetails(signImage: signImage[40], signDetails: signDetails[40]),
  RoadSignDetails(signImage: signImage[41], signDetails: signDetails[41]),
  RoadSignDetails(signImage: signImage[42], signDetails: signDetails[42]),
  RoadSignDetails(signImage: signImage[43], signDetails: signDetails[43]),
  RoadSignDetails(signImage: signImage[44], signDetails: signDetails[44]),
  RoadSignDetails(signImage: signImage[45], signDetails: signDetails[45]),
  RoadSignDetails(signImage: signImage[46], signDetails: signDetails[46]),
  RoadSignDetails(signImage: signImage[47], signDetails: signDetails[47]),
];
